auth/no_auth access
SigachevAV/JAQp pull request #29
Opened 2024-02-11 22:24 UTC by NaNinMind

добавил то, что сделал у себя, подогнал под новые названия и т.д.
api/image публичный доступ

2024-02-20 16:37 UTC, SigachevAV requested changes

2024-02-20 16:37 UTC, SigachevAV commented on JAQpApi/src/main/java/com/example/JAQpApi/Config/SecurityConfig.java
> +                        .requestMatchers("/api/image/**").permitAll()
Нам нужно только чтобы метод получения картинки был публичным, а тут разрешается всё. нужно или в контроллере поправить, или тут

2024-02-20 16:37 UTC, SigachevAV commented on JAQpApi/src/main/java/com/example/JAQpApi/Config/SecurityConstants.java
Я может глупый, но не логичнее это оставить в SecurityConfig.java?

2024-02-20 16:37 UTC, SigachevAV commented on JAQpApi/src/main/java/com/example/JAQpApi/DTO/RegistrationRequest.java
Я знаю что так правильнее, но не проще использовать готовый AuthenticationRequest ибо содержание у них одинаковое?

2024-02-21 08:28 UTC, NaNinMind commented on JAQpApi/src/main/java/com/example/JAQpApi/DTO/RegistrationRequest.java
правильнее и уже сделано, потом по-любому будут различия

2024-02-21 08:30 UTC, NaNinMind commented on JAQpApi/src/main/java/com/example/JAQpApi/Config/SecurityConstants.java
ну типа константы, че, потом может их будет много и тащить например таймауты оттуда надо будет

2024-02-21 08:31 UTC, NaNinMind commented on JAQpApi/src/main/java/com/example/JAQpApi/Config/SecurityConfig.java
> +                        .requestMatchers("/api/image/**").permitAll()
то есть только "api/image/{filename}" ?

2024-02-21 11:41 UTC, SigachevAV approved these changes

2024-02-21 11:51 UTC, merged